import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "CyberPunk",
  description: "Generated by create next app",
};
const febre_black = localFont({
  src: "../public/font/febreblack-regular.otf",
  variable: "--font-febre_black",
});
const airnt = localFont({
  src: "../public/font/Airnt.otf",
  variable: "--font-airnt",
});
const agency_fb = localFont({
  src: "../public/font/AGENCYR.ttf",
  variable: "--font-agency_fb",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${febre_black.variable} ${airnt.variable} ${agency_fb.variable} `}
    >
      <body>{children}</body>
    </html>
  );
}
